# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

development:
  adapter: sqlite3
  database: db/nvconfig.sql3
  pool: 5
  timeout: 5000

development2:
  adapter: sqlite3
  database: db/nvconfig.sql3
  pool: 5
  timeout: 5000

request_reply_db:
  adapter: sqlite3
  database:  db/req_rep.db
  pool: 5
  timeout: 5000
  
real_time_db:
  adapter: sqlite3
  database: db/rt.db
  pool: 5
  timeout: 5000

real_time_status_db:
  adapter: sqlite3
  database: db/rtstatus.sql3
  pool: 5
  timeout: 5000

mcf_db:
  adapter: sqlite3
  database: db/mcf.db
  pool: 5
  timeout: 5000

site_ptc_db:
  adapter: sqlite3
  database: db/InitialDB/iviu/GEOPTC.db
  pool: 5
  timeout: 500
  
log_db:
  adapter: sqlite3
  database: /usr/safetran/ramdb/log_db.db
  pool: 5
  timeout: 5000

oce_db:
  adapter: sqlite3
  database: db/oce.db
  pool: 5
  timeout: 5000


production:
  adapter: sqlite3
  database: db/nvconfig.sql3
  pool: 5
  timeout: 5000
  
