# SQLite version 3.x
databases:
  non_vital_config_db: /tmp/ramdb/nvconfig.sql3
  non_vital_config_backup_db: /mnt/logs/configs/nvconfig_backup.sql3
  non_vital_config_ecd_db: /mnt/ecd/0/nvconfig.sql3
  request_repl_db: /usr/safetran/ramdb/req_rep.db
  real_time_db: /usr/safetran/ramdb/rt.db
  real_time_status_db: /usr/safetran/ramdb/rtstatus.sql3
  mcf_db: /usr/safetran/db/mcf.db
  log_db: /usr/safetran/ramdb/log_db.db

program_set:
  V511: /usr/safetran/programset/9V512A01.*
  V374: /usr/safetran/programset/9V375A01.*
  V388: /usr/safetran/programset/9V389A01.*
  V973: /usr/safetran/programset/9v974A01.*
  V282: /usr/safetran/programset/9v141a01.*
  V900: /usr/safetran/programset/9V901B01.*
  V904: /usr/safetran/programset/9V905B01.*
  V838: /usr/safetran/programset/9v839B01.*
  V455: /usr/safetran/programset/9v459b01.*
  V354: /usr/safetran/programset/9v413b01.*
  V681: /usr/safetran/programset/9v765a01.*
  V565: /usr/safetran/programset/9V662A01.*
  V795: /usr/safetran/programset/9V796B01.*
  V665: /usr/safetran/programset/9v666B01.*
  V391: /usr/safetran/programset/9v414b01.*
  V785: /usr/safetran/programset/9v786b01.*
  V711: /usr/safetran/programset/9v712b01.*
  V461: /usr/safetran/programset/9v413b01.*
  V852: /usr/safetran/programset/9V853B01.*
  VA26: /usr/safetran/programset/9vA28A01.*
  VA19: /usr/safetran/programset/9vA20A01.*

# session settings in [seconds]
session:
  intervall: 5
  baudrate: 38400
  timeout: 30

# aux. files directory
aux_files:
  dir: /usr/safetran/dt

atcs:
  cpu_version: 5
  all_file_crc_subversion: 2
  geo_pci_msgs_state: 1

unsolicited_events:
  max_number_events: 500

request_reply:
  udp_ip_addr: 127.0.0.1
  udp_port: 33333
  locui_udp_port: 22222
  simple_request_timer_min: 15
  local_user_presence_ui_timeout: 30000

upload_directory:
  geo_software: /tmp/upload
  iviu_mcf: /mnt/ecd/mcf/mcfs
  iviu_pac: /tmp/upload
  iviu_mef: /tmp/upload
  iviu_nv_cfg: /tmp/upload
  iviu_nv_app: /tmp/upload
  iviu_v_cfg: /tmp/upload
  iviu_nv_rc2: /tmp/upload
  iviu_ldr_logic: /tmp/upload

report_files:
  dir: /usr/safetran/reports
  pac_download: /tmp/download

ecd:
  ecd_dir: /mnt/ecd
  download_dir: /mnt/ecd/0
  mcf_dir: /mnt/ecd/mcf/mcfs

debug:
  auxiliary_file_mgr: 0
  request_reply_mgr: 0
  db_mgr: 0
  atcs_local: 0
  protocols: 0
  diag_mgr: 0
  file_transfer: 0
  sniffer: 0
  logs: 0

local_ui:
  set_to_default_timeout: 60000
  local_user_presence_ui_timeout: 30000
  show_info_message: 0
  show_err_message: 0

status_update:
  local_ui_ptc: 3000
  local_ui_ech: 3000
  local_ui_eth: 3000

software_update:
 menu_wait_period: 15

geo_hist_log_all:
 filename: /tmp/log_all.txt

File_upload:
 target_vital_core_9v: 9VA49
 target_vital_core_executive: .mef
 target_vio_catrg_9v: 9VA58
 target_vio_catrg_executive: .mef

thread_excludes:
    ladder_logic: 1  ; Currently must run otherwise iVIU crashes
    diag_ui: 1
    telnet_monitor: 0
    cdl: 0
    wccmaint: 0
    wams: 0
    alarms: 0
    ulcp: 0
    vhfc: 0
    snmpmanager: 0
    itcstack: 0
    echif: 0
    icbcontrol: 0
    trackmon: 0

train_log_all:
 filename: /tmp/log_all.txt

track_mon:
    enabled: 1
    precount: 30
    postcount: 30
    logpath: /usr/safetran/tmp/

oce: 
  geo_aspect_file: 
  ptc_aspect_file: 
  IsDarkLsBitPosn: 8
  StaspLsBitPosn: 10
  AspLsBitPosn: 0
  T1LLsBitPosn: 9
  GCPSiteTemplate: 
log_download: 
  log_download_timeout: 1
WebUI: 
  single_user: 1
